server: 
  port: 8081
debug: true
logging: 
  level: 
    root: debug
    tk.mybatis.springboot.mapper: trace

#H2
spring:
    datasource: 
        url: jdbc:h2:mem:quartz
        driver-class-name: org.h2.Driver
        username: root
        password: 123456
        schema: classpath:db/schema.sql
        data: classpath:db/data.sql
    h2: 
      console: 
           path: /h2-console
           enabled: true
           settings: 
              web-allow-others: true